root: true
extends:
  - '@hydrooj/eslint-config'
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
      - .js
      - .jsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
rules:
  '@typescript-eslint/no-invalid-this': 1
  simple-import-sort/imports:
   - warn
   - groups:
     - ["^\\u0000"]
     - 
      - "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)"
      - "^(?!@?hydrooj)(@?\\w.+)"
      - "^@?hydrooj"
      - "^"
      - "^\\."
parserOptions:
  sourceType: module
#   project:
#     - './tsconfig.json'
#     - './packages/**/tsconfig.json'